using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Flynn1179.Observable;

string filename = Path.GetTempFileName();
string newFilename = Path.Combine(Path.GetDirectoryName(filename), "Test");
string thirdFilename = Path.Combine(Path.GetDirectoryName(filename), "Third");
Console.WriteLine("Changing " + filename + " to " + newFilename);
ObservableFile observableFile = new ObservableFile(filename);
observableFile.PropertyChanged += (sender, e) => Console.WriteLine("Detected change" + e.PropertyName);
Console.WriteLine("Filename currently: " + observableFile.Name);
File.Move(filename, newFilename);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Filename now:" + observableFile.Name);
File.Move(newFilename, thirdFilename);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Filename finally:" + observableFile.Name);
File.WriteAllText(thirdFilename, "Test");
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Updated Content");
File.Delete(thirdFilename);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Disposed? " + observableFile.IsDisposed);

string pathName = Path.Combine(Path.GetTempPath(), "ObservedFolder");
Directory.CreateDirectory(pathName);
string file1 = Path.Combine(pathName, Path.GetRandomFileName());
string file2 = Path.Combine(pathName, Path.GetRandomFileName());
string file3 = Path.Combine(pathName, Path.GetRandomFileName());
string folder1 = Path.Combine(pathName, Path.GetRandomFileName());
string folder2 = Path.Combine(pathName, Path.GetRandomFileName());
string subFile1 = Path.Combine(folder1, Path.GetRandomFileName());
File.WriteAllText(file1, "File1");
File.WriteAllText(file2, "File2");
ObservableDirectoryCollection observableDirectory = new ObservableDirectoryCollection(pathName) { Recursive = true };
observableDirectory.PropertyChanged += (sender, e) => Console.WriteLine("Folder property change: " + e.PropertyName);
observableDirectory.CollectionChanged += (sender, e) => Console.WriteLine("Folder content change: " + e.Action + ", " + e);
observableDirectory.Disposed += (sender, e) => Console.WriteLine("Disposing");

Console.WriteLine("New observable directory has " + observableDirectory.Count + " files");
Console.WriteLine("File 1 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file1, StringComparison.Ordinal)));
Console.WriteLine("File 2 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file2, StringComparison.Ordinal)));
Console.WriteLine("File 3 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file3, StringComparison.Ordinal)));
File.WriteAllText(file3, "File3");
System.Threading.Thread.Sleep(1000);
Console.WriteLine("File 1 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file1, StringComparison.Ordinal)));
Console.WriteLine("File 2 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file2, StringComparison.Ordinal)));
Console.WriteLine("File 3 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file3, StringComparison.Ordinal)));
File.Delete(file2);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("File 1 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file1, StringComparison.Ordinal)));
Console.WriteLine("File 2 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file2, StringComparison.Ordinal)));
Console.WriteLine("File 3 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file3, StringComparison.Ordinal)));
string file4 = Path.GetTempFileName();
File.Move(file4, file2);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("File 1 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file1, StringComparison.Ordinal)));
Console.WriteLine("File 2 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file2, StringComparison.Ordinal)));
Console.WriteLine("File 3 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file3, StringComparison.Ordinal)));
File.Move(file3, file4);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("File 1 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file1, StringComparison.Ordinal)));
Console.WriteLine("File 2 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file2, StringComparison.Ordinal)));
Console.WriteLine("File 3 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file3, StringComparison.Ordinal)));
Console.WriteLine("File 4 present: " + observableDirectory.Any(file => string.Equals(file.FullPath, file4, StringComparison.Ordinal)));
Directory.CreateDirectory(folder1);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Folder present: " + observableDirectory.Any(file => string.Equals(file.FullPath, folder1, StringComparison.Ordinal)));
ObservableDirectoryCollection observableSubDirectory = observableDirectory.OfType<ObservableDirectoryCollection>().FirstOrDefault(file => string.Equals(file.FullPath, folder1, StringComparison.Ordinal));
Console.WriteLine("Observable subdirectory present:" + (observableSubDirectory is not null));
File.WriteAllText(subFile1, "SubFile1");
System.Threading.Thread.Sleep(1000);
Console.WriteLine("File 1 present: " + observableSubDirectory.Any(file => string.Equals(file.FullPath, subFile1, StringComparison.Ordinal)));
File.Delete(file1);
File.Delete(file2);
File.Delete(file4);
Directory.Delete(pathName, true);
System.Threading.Thread.Sleep(1000);
Console.WriteLine("Folder disposed: " + observableDirectory.IsDisposed);
Console.WriteLine("Subfolder disposed: " + observableSubDirectory.IsDisposed);

Console.ReadKey();
